server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**,/api/v1/auth/**
              filters:
                - StripPrefix=0

            - id: event-service
              uri: lb://event-service
              predicates:
                - Path=/api/v1/events/**,/api/v1/categories/**,/api/v1/venues,/api/v1/events/{id}/ticket-types, /api/v1/ticket-types/**
              filters:
                - StripPrefix=0

            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/v1/inventory/**,/api/v1/holds/**
              filters:
                - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway